# ## Задача: Роль security_hardening
# - **Статус**: В процессе
# - **Описание**: Дефолтные параметры firewalld и SELinux.
selinux_target_mode: Enforcing
firewalld_enabled: true
firewall_allowed_protocols: []
