# ## Задача: Роль container_runtime
# - **Статус**: В процессе
# - **Описание**: Дефолтные параметры container runtime.
container_runtime_name: containerd
container_runtime_manage_config: true
container_runtime_install_cri_tools: false
container_runtime_cri_tools_package: cri-tools

container_runtime_packages_map:
  containerd:
    - containerd
  crio:
    - cri-o

containerd_config_path: /etc/containerd/config.toml
containerd_sandbox_image: registry.k8s.io/pause:3.9
